apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: bhargavibairagoni/wordpress:wordimage 
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          value: "mysql:3306"  # Point to the MySQL service
        - name: WORDPRESS_DB_NAME
          value: "wordpress"  # Database name for WordPress
        - name: WORDPRESS_DB_USER
          value: "admin"  # MySQL username (same as in MySQL Deployment)
        - name: WORDPRESS_DB_PASSWORD
          value: "ADMIN123"  # MySQL password (same as in MySQL Deployment)
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # Can be ClusterIP for internal access only
